config/routes.rb
Rails.application.routes.draw do
  # mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
	root "blogs#index"
  resources :blogs do
 	resources :votes, only: [:create, :destroy]
	end
 end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

	belongs_to :user
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         #relationships
         has_many :blogs, dependent: :destroy
end

app/models/vote.rb
class Vote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit 
  protect_from_forgery with: :exception
  # rescue from pundit by going the function
 rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
 private
 # alert user for unauthorized usage
 def user_not_authorized
 flash[:alert] = "You are not authorized to perform this action."
 redirect_to(request.referrer || root_path)
 end 
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new, :update, :destroy]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]


  def index
    @blogs = Blog.all
  end


  def show
  end


  def new
    @blog = Blog.new
  end


  def edit
    authorize @blog 
  end


  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @blog
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    # authorize @blog 
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_blog
      @blog = Blog.find(params[:id])
    end

    
    def blog_params
      params.require(:blog).permit(:title, :content, :publish)
    end
end

app/controllers/votes.controller.rb
class VotesController < ApplicationController
 before_action :authenticate_user!
 before_action :set_blog 
 def create
 @vote = Vote.new
 @vote.blog = @blog
 @vote.user = current_user
 @vote.save
 redirect_to :back
 end
 def destroy
 @vote = @blog.votes.find(params[:id])
 @vote.destroy
 redirect_to :back
 end
 private
 def set_blog
 @blog = Blog.find(params[:blog_id])
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class="row">
 <div class="col s12">
 <div class="card-panel">
 <%= form_for(@blog) do |f| %>

 <!-- blog title -->
 <div class="input-field"> 
 <%= f.label :title %>
 <%= f.text_field :title, required: true, autofocus: true %>
 </div>

 <!-- blog content -->
 <div class="input-field">
 <%= f.label :content %>
 <%= f.text_area :content, id: "blog_content", required: true,
class: "materialize-textarea" %>
 </div>

 <!-- Submit form -->
 <div class="input-field center">
 <%= f.submit button, class: "btn" %>
 </div>
 <% end %>
 </div>
 </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
 <h1 class="center">Edit <%= @blog.title.truncate(15) %></h1>
 <%= render partial:'form', locals: {button: "Save Blog"} %>
</div> 

app/views/blogs/index.html.erb
<div class="container">
 <!-- Fixed New blog button -->
 <div class="fixed-action-btn" style="top: 50px; right: 24px;">
 <a class="btn-floating btn-large red" href="<%= new_blog_path %>">
 <i class="large material-icons">add</i>
 </a>
 </div>
 <!-- Header of index-->
 <h1 class="center">Lozo's Blogs</h1>
 <!-- Indexes -->
 <div class="row">
 <!-- Handling each blog separate -->
 <% @blogs.each do |blog| %>
 <%= link_to blog_path(blog) do %>
 <div class="col s12 m4">
 <div class="card">
 <div class="card-content black-text"> 

 <span class="card-title black-text"><%= blog.title
  %></span>
  <p><%= blog.content.truncate(300, separator: " ")
  %></p>
  </div>
    </div>
      </div>
        <% end %>
          <% end %>
              </div>
                </div>

app/views/blogs/new.html.erb
<div class="container">
<h1 class="center">New Blog</h1>
<%= render partial:'form', locals: {button: "Create Blog"} %>
</div> 

app/views/blogs/show.html.erb
<div class="container">
 <div class="row">
 <div class="col s12">
 <div class="card-panel">
 <h1 class="center"><%= @blog.title %></h1>
 <div class="center">
 <%= link_to '<i class="material-icons">mode_edit</i>'.html_safe,
edit_blog_path(@blog), class: "btn blue" %> 
 <%= link_to '<i class="material-icons">delete</i>'.html_safe,
@blog, method: :delete, data: { confirm: 'Are you sure?' },
class: "btn red" %>
 </div>
 <hr/>
 <p><%= @blog.content %></p>
 </div>
 </div>
 </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <!-- let browser know website is optimized for mobile -->
   <meta name="viewport" content="width=device-width, initialscale=1.0"/>
    <title>BlogPro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'%>

    <!--Import Google Icon Font-->
 <link href="http://fonts.googleapis.com/icon?family=Material+Icons"
rel="stylesheet"> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%=render 'shared/topNav'%>
  <main>
    <%= yield %>
  </main>
  <%= render 'shared/footer'%>
  </body>
</html>

app/views/shared/_footer.html.erb
<nav style="background-color: rgba(158, 158, 158, 0.21);">
 <div class="nav-wrapper">
 <a href=" https://www.linkedin.com/in/carlos-rivera-8268324b/" style="color: #99ADEB; marginright:
10px;" class="right"> Copyright &copy; Carlos Rivera</a>
 </div>
</nav> 

app/views/shared/_navElements.html.erb
<li class="<%= "active" if controller_name == "blogs" %>"><%= link_to "Blogs", root_path %></li>
<% if user_signed_in? %>
 <li class="<%= "active" if current_page?(edit_user_registration_path) %>"><%= link_to "Edit Profile", edit_user_registration_path %></
li>
 <li><%= link_to "Log Out", destroy_user_session_path,
method: :delete %></li>
<% else %>
 <li class="<%= "active" if current_page?(new_user_session_path)
%>"><%= link_to "Log In", new_user_session_path %></li>
 <li class="<%= "active" if current_page?(new_user_registration_path) %>"><%= link_to "Sign Up", new_user_registration_path %></li>
<% end %>

app/views/shared/_topNav.html.erb
	

	<nav style="background-color:   red;">
 	<div class="nav-wrapper">
 <a href="<%= root_path %>" class="brand-logo"> Home </a> 
 <a href="#" data-activates="mobile-demo" class="button-collapse"><i
	 class="material-icons">menu</i></a>
 <ul class="right hide-on-med-and-down">
 <%= render "shared/navElements" %> 
 </ul>
 	<ul class="side-nav" id="mobile-demo">
 <%= render "shared/navElements" %> 
 </ul>
 </div>
</nav> 